name: Convert CSV to JSON

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Convert CSV to JSON
        run: |
          python csv_to_json.py input.csv output.json

      - name: Upload JSON as artifact
        uses: actions/upload-artifact@v2
        with:
          name: json-artifact
          path: output.json
