name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # oder eine andere Version, die du benötigst
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Hier kannst du weitere Abhängigkeiten installieren, wenn du eine requirements.txt hast
        # pip install -r requirements.txt
    - name: Run script
      run: |
        python main.py
